//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsemkaHero
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EsemkaHeroEntities : DbContext
    {
        public EsemkaHeroEntities()
            : base("name=EsemkaHeroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clan> Clans { get; set; }
        public virtual DbSet<Element> Elements { get; set; }
        public virtual DbSet<FightHistory> FightHistories { get; set; }
        public virtual DbSet<Hero> Heroes { get; set; }
        public virtual DbSet<HeroSkill> HeroSkills { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
    }
}
